FROM node:latest as node
LABEL maintainer="ticquique@gmail.com"

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    vim \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app
COPY ./angular/package*.json ./
RUN npm install

COPY ./angular .
CMD npm run start