version: "3.7"
services:
  cron:
    build: cron-retrieval
    container_name: wow_cron
    environment:
      - WOW_SECRET=${WOW_SECRET}
      - WOW_ID=${WOW_ID}

  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - PRODUCTION=${PRODUCTION:-false}
    volumes:
      - ./db:/data/db
    command: --smallfiles

  angular:
    build: frontend
    restart: always
    environment:
      - TZ=UTC
      - PRODUCTION=${PRODUCTION:-false}
      - APP_DOMAIN=${APP_DOMAIN:-wow.webynav.com}
      - APP_DOMAIN_DEV=${APP_DOMAIN_DEV:-localhost}