version: "3"
services:
  cron:
    build: cron-retrieval
    container_name: wow_cron
    volumes:
      - ./cron-retrieval/retriever.sh:/home/retriever.sh
      - ./cron-retrieval/results:/home/results
    environment:
      - WOW_SECRET=${WOW_SECRET}
      - WOW_ID=${WOW_ID}

  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - PRODUCTION=${PRODUCTION:-false}
    volumes:
      - ./db:/data/db
    command: --smallfiles

  angular:
    image: nginx
    volumes:
      - ./frontend/dist:/var/www/html
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9090:80"
    restart: always
    environment:
      - TZ=UTC
      - PRODUCTION=${PRODUCTION:-false}
      - APP_DOMAIN=${APP_DOMAIN:-wow.webynav.com}
      - APP_DOMAIN_DEV=${APP_DOMAIN_DEV:-localhost}