version: "3.6"
services:
  cron:
    build: cron-retrieval
    container_name: wow_cron
    environment:
      - WOW_SECRET=${WOW_SECRET}
      - WOW_ID=${WOW_ID}

  angular:
    build: frontend
    restart: always
    environment:
      - TZ=UTC
      - PRODUCTION=${PRODUCTION:-false}
      - APP_DOMAIN=${APP_DOMAIN:-wow.webynav.com}
      - APP_DOMAIN_DEV=${APP_DOMAIN_DEV:-localhost}

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: wow_db
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=\"*\""
      - "http.cors.allow-methods=OPTIONS, HEAD, GET, POST, PUT, DELETE"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type, Content-Length"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
    driver: local

